# Create a secret to save sensitive configs
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: e-commerce # Add it to "e-commerce" namespace
  labels: # Add a label to make it easy to identify
    app: e-commerce
    module: configs
stringData: # In real application, use sealed-secrets/vault/kamus.
  # NOTE: To get username and credential, use the command listed here https://www.rabbitmq.com/kubernetes/operator/using-operator#creds.
  AMPQ_USERNAME: default_user_9QCIaVWyw_RxKcDRYc4
  AMPQ_PASSWORD: yPfQu4vwdCA1yVRMI3tcmA4IB_cYjKnU

