apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
  namespace: karsajobs
  labels:
    app: karsajobs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/mbishram/karsajobs:latest
          ports:
            - containerPort: 8080
              name: karsajobs
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: $(MONGO_SERVICE_SERVICE_HOST)
              #value: localhost # Using docker desktop k8s. NOTE: Headless service doesn't work on local, I'm not sure why
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
