apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: karsajobs
  labels:
    app: karsajobs
    tier: data
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: data
  template:
    metadata:
      labels:
        app: karsajobs
        tier: data
    spec:
      containers:
        - name: data
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: mongo-pvc
            - mountPath: /config
              name: mongo-config
            - mountPath: /etc/mongo-credentials
              name: mongo-secret
      volumes:
        - name: mongo-pvc
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongo-config
          configMap:
            name: mongo-config
        - name: mongo-secret
          secret:
            secretName: mongo-secret

