apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: karsajobs
  labels:
    app: karsajobs
    tier: data
spec:
  selector:
    app: karsajobs
    tier: data
  ports:
    - port: 27017
      targetPort: mongo
  clusterIP: None