apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: karsajobs
  labels:
    app: karsajobs
    tier: data
spec:
  selector:
    app: karsajobs
    tier: data
  ports:
    - port: 27017
      targetPort: mongo
  clusterIP: None # Headless service. NOTE: It doesn't work on local. While using docker desktop k8s, trying to access them on localhost:27017 doesn't work.