apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: karsajobs
  labels:
    app: karsajobs
    tier: data
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mtn/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: karsajobs
  labels:
    app: karsajobs
    tier: data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi