name: Lint and Build

on: [push]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    env:
      CR_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: bash build_push_image_karsajobs_ui.sh
